apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ep
spec:
  rules:
  - host: {{ .Values.EP_FQDN }}
    http:
      paths:
      - backend:
          service:
            name: ep
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.EP_FQDN }}
    secretName: {{ .Values.TLS_SECRET }}
---
apiVersion: v1
kind: Service
metadata:
  name: ep
spec:
  type: ClusterIP
  selector:
    app: ep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ep
  template:
    metadata:
      labels:
        app: ep
    spec:
      imagePullSecrets:
      - name: ep-ghcr
      containers:
        - name: boluswizard
          image: ghcr.io/delduked/extrusion_profiles/ui:v{{ .Values.VERSION }} # change this in pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 80
