name: deploy to bwdev namespace
on:
  push:
    branches:
      - build/*

jobs:
  build:
    runs-on: [self-hosted, ghost-pop]
    steps:
      - uses: actions/checkout@v3
      - name: Get version from package.json
        id: package_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Package version: $VERSION"
          echo "::set-output name=version::$VERSION"
      - name: Build Go UI image
        run : |
          echo "building extrusion_profiles/ui image"
          export CR_PAT=${{ secrets.ALL_ACCESS_PAT }} ; echo $CR_PAT | docker login ghcr.io -u delduked --password-stdin
          docker build -t ghcr.io/delduked/extrusion_profiles/ui:v${{steps.package_version.outputs.VERSION}} ./ -f ./ui.dockerfile
          docker push ghcr.io/delduked/extrusion_profiles/ui:v${{steps.package_version.outputs.VERSION}}
    